### PR TITLE
Edited Player.cs script

### PR DESCRIPTION
**Pull request by MrAfitol**
- Added method RemoveItem
- Added method DropItem
- Edited method AddItem

### CODE REVIEW

**Comment by moddedmcplayer** [comment]
Isn't there another pr already adding the AddItem method?

**Comment by MrAfitol** [comment]
> Isn't there another pr already adding the AddItem method?

I didn't add it, I edited it

**Comment by moddedmcplayer** [comment]
Yeah #114

**Comment by moddedmcplayer** [comment]
Oh wait

**Comment by moddedmcplayer** [comment]
The edit looks good, but any reason to use serials?

**Comment by moddedmcplayer** [comment]
And your xml docs sadly don't seem to follow standard format

**Comment by MrAfitol** [comment]
> 

Sorry, I didn't quite understand, do you mean item serials?

**Comment by MrAfitol** [comment]
> And your xml docs sadly don't seem to follow standard format

Please check the xml documents again

**Comment by moddedmcplayer** [comment]
That's better, just some general rules is that they typically will just skip the Returns start since the IDE probably already has it when showing the docs, and they should always end with a full stop. 
Your IDE should have probably highlighted this.

**Comment by moddedmcplayer** [comment]
> Sorry, I didn't quite understand, do you mean item serials?

The param, any reason to use it?

**Comment by MrAfitol** [comment]
> > Sorry, I didn't quite understand, do you mean item serials?
> 
> The param, any reason to use it?

Do you want me to write in the code what it is for, or explain to you?

**Comment by moddedmcplayer** [comment]
> > > Sorry, I didn't quite understand, do you mean item serials?
> > 
> > The param, any reason to use it?
> 
> Do you want me to write in the code what it is for, or explain to you?

Explain to me why we need ItemSerial and cant get it from ItemBase

**Comment by MrAfitol** [comment]
> > > > Sorry, I didn't quite understand, do you mean item serials?
> > > 
> > > 
> > > The param, any reason to use it?
> > 
> > 
> > Do you want me to write in the code what it is for, or explain to you?
> 
> Explain to me why we need ItemSerial and cant get it from ItemBase

Do you mean for people to only pass ItemBasePickup?

**Comment by moddedmcplayer** [comment]
Yeah

**Comment by moddedmcplayer** [comment]
Lastly we should probably use the wrapper already in the API instead of the basegame method

**Comment by MrAfitol** [comment]
> Lastly we should probably use the wrapper already in the API instead of the basegame type

As I understand it, there is no need to make any more amendments?

**Comment by moddedmcplayer** [comment]
> > Lastly we should probably use the wrapper already in the API instead of the basegame type
> 
> 
> 
> As I understand it, there is no need to make any more amendments?

We want people to use the Item class from the PluginAPI.Core namespace, otherwise it wouldn't exist. Change ItemBase to Item and we should be good.

**Comment by MrAfitol** [comment]
> We want people to use the Item class from the PluginAPI.Core namespace, otherwise it wouldn't exist. Change ItemBase to Item and we should be good.

That's how I understood it, now I'll post a commit

**Pull request merged**
