### PR TITLE
Taking us out of the hell of parameters

### PR DESCRIPTION
**Pull request by SrLicht**
# Removing the way the parameters are currently obtained and changing it to EventArgs
This will help to better understand the API to know what can be changed and what can't (since if it can't be changed you just put GET and that's it) apart from the fact that you can document the variables.

# EventArgs

## Player

 * Added ActivatingGeneratorEventArgs
 * Added AimingWeaponEventArgs
 * Added BanningEventArgs
 * Added CancellingItemUseEventArgs
 * Added ChangingItemEventArgs
 * Added ChangingRadioRangeEventArgs
 * Added ChangingRoleEventArgs
 * Added ChangingSpectatedPlayerEventArgs
 * Added ClosingGeneratorEventArgs
 * Added DamagingPlayerEventArgs
 * Added DamagingShootingTargetEventArgs
 * Added DamagingWindowEventArgs
 * Added DeactivatingGeneratorEventArgs
 * Added DiedEventArgs
 * Added DroppingAmmoEventArgs
 * Added DroppingItemEventArgs
 * Added DryWeaponEventArgs
 * Added DyingEventArgs
 * Added EnteringPocketDimensionEventArgs
 * Added EscapingEventArgs
 * Added FinishExecutingGameConsoleCommandEventArgs
 * Added FinishExecutingRaCommandEventArgs
 * Added FlippedCoinEventArgs
 * Added FlippingCoinEventArgs
 * Added GettingGroupEventArgs
 * Added HandcuffingEventArgs
 * Added InteractingDoorEventArgs
 * Added InteractingElevatorEventArgs
 * Added InteractingGeneratorEventArgs
 * Added InteractingLockerEventArgs
 * Added InteractingShootingTargetEventArgs
 * Added JoinedEventArgs
 * Added KickingEventArgs
 * Added LeftEventArgs
 * Added MakingNoiseEventArgs
 * Added MutedEventArgs
 * Added OpeningGeneratorEventArgs
 * Added PickingUpAmmoEventArgs
 * Added PickingUpArmorEventArgs
 * Added PreAuthenticatingEventArgs
 * Added ReceivingEffectEventArgs
 * Added ReloadingWeaponEventArgs
 * Added RemovingHandcuffsEventArgs
 * Added ReservedSlotsCheckEventArgs
 * Added SearchedPickupEventArgs
 * Added SearchingPickupEventArgs
 * Added ShootingEventArgs
 * Added SpawningEventArgs
 * Added SpawningRagdollEventArgs
 * Added ThrowingItemEventArgs
 * Added ThrowingProjectileEventArgs
 * Added ToggledRadioEventArgs
 * Added TogglingFlashlightEventArgs
 * Added TryEscapingPocketDimensionEventArgs
 * Added UnloadingWeapon
 * Added UnlockingGeneratorEventArgs
 * Added UnMuteEventArgs
 * Added UsedItemEventArgs
 * Added UsingGameConsoleCommand
 * Added UsingHotkeyEventArgs
 * Added UsingIntercomEventArgs
 * Added UsingItemEventArgs
 * Added UsingRaCommandEventArgs

## SCP-079

 * Added CameraChangedEventArgs
 * Added BlackoutRoomEventArgs
 * Added BlackoutZoneEventArgs
 * Added CancelsDoorLockdownEventArgs
 * Added CancelsRoomLockdownEventArgs
 * Added GainExperienceEventArgs
 * Added GainLevelEventArgs
 * Added LockingDownDoorEventArgs
 * Added LockingDownRoomEventArgs
 * Added PiningEventArgs
 * Added UsingTeslaEventArgs

## SCP-049

 * Added CallProgenyEventArgs
 * Added FailsMarkingTargetEventArgs
 * Added KillMarkedPlayerEventArgs
 * Added LoseMarkEventArgs
 * Added MarkTargetEventArgs 
 * Added ResurrectBodyEventArgs
 * Added StartingResurrectionEventArgs

## SCP-096

 * Added AddingTargetEventArg
 * Added ChangeStateEventArgs
 * Added ChargingEventArgs
 * Added EnragingEventArgs
 * Added PryingGateEventArgs
 * Added SlapPlayerEventArgs
 * Added StartCryingEventArgs
 * Added TryNotCryEventArg

## SCP-106

 * Added KidnappingPlayerEventArgs
 * Added StalkingEventArgs
 * Added TeleportingEventArgs

## SCP-173

 * Added NewObserverEventArgs
 * Added PlacingTantrumEventArgs
 * Added PlayingSoundEventArgs
 * Added SnapPlayerNeckEventArgs
 * Added UsingBreakneckSpeedsEventArgs

## SCP-049-2

 * Added ConsumeCorpseEventArgs 

## SCP-939

 * Added CreatingAmnesticCloudEventArgs
 * Added LungeEventArgs
 * Added Scp939AttackEventArgs

## SCP-914

 * Added ActivatingEventArgs
 * Added ChangingKnobSettingEventArgs
 * Added ProcessingPlayerEventArgs
 * Added UpgradedInventoryItemEventArgs
 * Added UpgradedPickupEventArgs
 * Added UpgradingInventoryItemEventArgs
 * Added UpgradingPickupEventArgs

## SCP-330

 * Added InteractingScp330EventArgs
 * Added PickingUpScp330EventArgs

## Server

 * Added AddingUnitNameEventArgs
 * Added EndingRoundEventArgs
 * Added MapGeneratedEventArgs
 * Added ReportingCheaterEventArgs
 * Added TeamRespawningEventArgs
 * Added TeamRespawnSelectedEventArgs
 * Added BanIssuedEventArgs
 * Added BanRevokedEventArgs
 * Added BanUpdatingEventArgs
 * Added CheckingRoundEndConditionsEventArgs
 * Added FinishExecutingConsoleCommand
 * Added UseConsoleCommandEventArgs

## Map

 * Added AnnouncingDecontaminationEventArgs
 * Added DecontaminatingEventArgs (No really needed)
 * Added ExplodingGrenadeEventArgs
 * Added GeneratorActivatedEventArgs
 * Added PlacingBloodEventArgs
 * Added PlacingBulletHoleEventArgs
 * Added SpawningItemEventArgs
 * Added AnnouncingScpTerminationEventArgs

## Warhead

 * Added StartingEventArgs
 * Added StoppingEventArgs

> Probably not all EventArgs are here and it's because I've been programming this for more than 6 hours and my brain thinks of nothing but my bed at this point.

# New Events
Taking advantage of the fact that he was doing this, i wants to add more events, more is better.

 * Added Scp0492ConsumedCorpse (Executed in ZombieConsumeAbility.ServerComplete, need to modify this class a little bit since I want to get the ragdoll.)

 * Added Scp106UsingHunterAtlas (Executed in Scp106HuntersAtlasAbility.ServerProcessCmd )

 * Added Scp096SlapPlayer (Executed in Scp096AttackAbility.ServerAttack, i want to get and change the damage, since currently to do this I have to either make a patch or put horrible code in DamagingPlayerEventArgs )

 * Added Scp079Pining (Executed in Scp079PingAbility.ServerProcessCmd)

 * Added Scp049CallProgeny (Executed in Scp049CallAbility.ServerProcessCmd)

 * Added Scp049FailsMarkPlayer (Executed in Scp049SenseAbility.ServerProcessCmd)

 * Added Scp049KillMarkedPlayer (Executed in Scp049SenseAbility.ServerProcesssKilledPlayer)

 * Added Scp049LosingMarkedPlayer (Executed in Scp049SenseAbility.ServerLoseTarget)

 * Added Scp049MarkingPlayer (Executed in Scp049SenseAbility.ServerProcessCmd)

### Done finally finished, now accept this or I kill a Capybara, DID YOU HEARD THAT HUBERT !!!!!

### CODE REVIEW

**Comment by SrLicht** [comment]
My hands hurt.

**Comment by ItzPeaxel** [comment]
We need this on nwapi ASAP ! :(

**Comment by moddedmcplayer** [comment]
Tbh just marking all Parameters as ref would d the job just fine

**Comment by SrLicht** [comment]
> Tbh just marking all Parameters as ref would d the job just fine

could you explain?

**Comment by moddedmcplayer** [comment]
> > Tbh just marking all Parameters as ref would d the job just fine
> 
> could you explain?

instead of (EventParams ev) youd have (ref bool Allowed, Player attack, ref float damage) etc. (attacker not ref since object anyways + shouldnt be changed)

**Comment by SrLicht** [comment]
> > > Tbh just marking all Parameters as ref would d the job just fine
> > 
> > 
> > could you explain?
> 
> instead of (EventParams ev) youd have (ref bool Allowed, Player attack, ref float damage) etc. (attacker not ref since object anyways + shouldnt be changed)

My problem with the parameters is that if an event has 6 parameters and you only use 1, you necessarily have to write all 6 because otherwise the code gives an error, that's why I prefer the EventArgs, there is also that they cannot be documented and you don't know what they do each until you read the documentation (which doesn't exist) another problem that an EventArgs fixes. If it is because of IsAllowed, it is possible to add it, but it is more part of Northowood than of the PR because this change only makes them have to do DyingEventArgs ev = new (player, tager, amoun, damagehandler) instead, put IsAllowed, they have to modify as described they execute the events that is more work, apart from the fact that I am already doubting that they are going to accept this PR

**Comment by moddedmcplayer** [comment]
1.) Just make it only throw when types are incorrect so (Player, bool) would still be valid for a (Player, bool, float) event
2.) Issue with Nuget publishing, not code

**Comment by KarlOfDuty** [comment]
:+1: This would make things much cleaner in functions with a lot of parameters and all events much more maintainable.

**Comment by XLittleLeft** [comment]
RemoteAdminEvent(Player user, string command)
i need it

**Comment by XLittleLeft** [comment]
make a enum RemoteAdminCommandType
then
RemoteAdminEvent(Player user, RemoteAdminCommandType type,string command)

**Comment by moddedmcplayer** [comment]
But how is that related? If you really need it, patch it.

**Comment by XLittleLeft** [comment]
> But how is that related? If you really need it, patch it.

i mean i wanna this event,plz make it

**Comment by moddedmcplayer** [comment]
> > But how is that related? If you really need it, patch it.
> 
> i mean i wanna this event,plz make it

But why write it here instead of somewhere the devs will actually consider it?

**Comment by XLittleLeft** [comment]
> > > But how is that related? If you really need it, patch it.
> > 
> > 
> > i mean i wanna this event,plz make it
> 
> But why write it here instead of somewhere the devs will actually consider it?


> > > But how is that related? If you really need it, patch it.
> > 
> > 
> > i mean i wanna this event,plz make it
> 
> But why write it here instead of somewhere the devs will actually consider it?

i saw SrLicht adding event

**Comment by SrLicht** [comment]
This PR is meaningless since NW will implement the EventArgs themselves.

**Pull request closed without merging**
