### PR TITLE
MessageTranslated for CASSIE

### PR DESCRIPTION
**Pull request by SrLicht**
I better have it in the API than an extension in every damn plugin I create

### CODE REVIEW

**Comment by louis1706** [comment]
Can you add comment made By Yamato from Exiled

**Comment by xNexus-ACS** [comment]
@SrLicht you have literaly copied the exiled method lmao

**Comment by SrLicht** [comment]
> @SrLicht you have literaly copied the exiled method lmao, at least give credits lol

As the description of the PR says, it is an extension that has existed for almost a year in my main plugin. It is taken from Exiled and I will give credit to https://github.com/louis1706, which according to Git blame he created the method, honestly I never searched for it.

**Comment by SrLicht** [comment]
> Can you add comment made By Yamato from Exiled

My most sincere apologies for not putting the credit, now I fix it

**Comment by louis1706** [comment]
thanks ❤️

**Comment by moddedmcplayer** [comment]
Or slightly change it and not have to put Exiled credit in the docs which will probably most definitely make certain people unhappy.

**Comment by louis1706** [comment]
> Or slightly change it and not have to put Exiled credit in the docs which will probably most definitely make certain people unhappy.
> 

Why it's would make people unhappy?!

**Comment by KarlOfDuty** [comment]
Imo that kind of stuff should be in the commit info, not in the code. There shouldn't be comments just for stating who did things.

**Comment by SrLicht** [comment]
So do what you want, I'm not going to change the code every now and then to satisfy everyone, you do the PR and have fun.

**Pull request closed without merging**
