### PR TITLE
Small stamina addition

### PR DESCRIPTION
**Pull request by Bonjemus**
Don't worry, I didn't make 1,183 additions and 1,174 deletions.

### CODE REVIEW

**Comment by moddedmcplayer** [comment]
You fix your ide and redo this thing. It's basically impossible to review this.

**Comment by zabszk** [comment]
> You fix your ide and redo this thing. It's basically impossible to review this.

Actually this file for some reason wasn't following the .editorconfig file and @Bonjemus 's IDE automatically fixed the new line styles according to the .editorconfig file.

GitHub allows you to hide whitespace changes during the review and it's really useful in this case.

**Review by zabszk — APPROVED** [review]

**Comment by Bonjemus** [comment]
> You fix your ide and redo this thing. It's basically impossible to review this.

I don't think my IDE is broken, sorry for the inconvenience though.

**Comment by zabszk** [comment]
> > You fix your ide and redo this thing. It's basically impossible to review this.
> 
> I don't think my IDE is broken, sorry for the inconvenience though.

Your IDE isn't broken. It just followed the .editorconfig file of this repository. That file was broken (it didn't follow the .editorconfig file) and your IDE automatically "fixed" the file.

**Review by Killers0992 — APPROVED** [review]

**Pull request merged**
